name: Release

on:
    push:
        tags:
            - '*'

jobs:
    release:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - uses: actions/checkout@v3
            - uses: oven-sh/setup-bun@v1

            - run: bun install
            - run: bun run package
            - uses: ncipollo/release-action@v1
              with:
                  artifacts: 'gpt-commit'
